### ISSUE TITLE
fixing README

### ISSUE THREAD

**Issue by mani144** [FrogSquare/GodotGoogleService#18]
Hi,

i tried to follow the readme step but it seems old 
this repo is not avalible anymore, can you please update it :
git clone https://github.com/FrogSquare/GodotGoogleAds GodotGoogleAds

**Comment by FlavioFS** [comment]
@mani144 
He seems to have changed the repo name to GodotAds:
```git clone https://github.com/FrogSquare/GodotAds GodotAds```
