### ISSUE TITLE
Gradlew build fails

### ISSUE THREAD

**Issue by FlavioFS** [FrogSquare/GodotGoogleService#21]
I cannot build it becaus Gradlew fails. This module misses some google services json file.   
**Ubuntu 18.04.2 LTS**  
Modules:  
 - GodotAds
 - GodotGoogleService
 - GodotSql
```bash
> Task :checkDebugClasspath 
Warning: The app gradle file must have a dependency on com.google.firebase:firebase-core for Firebase services to work as intended.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /home/username/repos/godot31/platform/android/java/src/nullnull/debug/google-services.json
  /home/username/repos/godot31/platform/android/java/src/debug/nullnull/google-services.json
  /home/username/repos/godot31/platform/android/java/src/nullnull/google-services.json
  /home/username/repos/godot31/platform/android/java/src/debug/google-services.json
  /home/username/repos/godot31/platform/android/java/src/nullnullDebug/google-services.json
  /home/username/repos/godot31/platform/android/java/google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s
10 actionable tasks: 10 executed
```

**Comment by RameshRavone** [comment]
You need to download the google-service.json file from play store console

**Comment by FlavioFS** [comment]
Sorry if my question is basic, I am not much into Google's APIs.
Where should I place that file?

**Comment by FlavioFS** [comment]
Now I am starting to remember that resources xml in Play Services Console. Is that one you mean? The one with the achievements, leaderboards etc?

**Comment by RameshRavone** [comment]
At, `GODOT_SRC/platform/android/java/`

You could read the README.md file you know

**Comment by FlavioFS** [comment]
I've read the README file so many times. O.o
I didn't see anything about this json file. Maybe I'm just so tired of trying to compile this I can't even think correctly anymore. More than a week trying to get this to work. xD

**Comment by FlavioFS** [comment]
Ctrl + F README, typed "json". No ocurrences. Is it really there? o.o"

**Comment by RameshRavone** [comment]
Hmmm, seems I didn't add it there, a lot is missing, well I'll fix that
with my next push to support godot 3.2

**Comment by FlavioFS** [comment]
Ty, I 'll keep trying to get this json file. Google is driving me crazy already, lol.

**Comment by FlavioFS** [comment]
Just one last question... Do I need a Firebase project to download that json file? Please say no, haha

**Comment by FlavioFS** [comment]
Yeah... I had to go to [Firebase Console](https://console.firebase.google.com) and link my Android app to get the file...
Why, Google? Why...?

**Comment by RameshRavone** [comment]
The reason for using google-service.json file is for convenience the file
will have a lot of details on ids and signs that will be good for apk sign
and verification google does some complecated stuff in its publisher
console it always crazy, but once every thing is done, you game/app will be
secure (well that is what google says anyway)

**Comment by FlavioFS** [comment]
Downloading json from Firebase worked indeed, ty for the fast reply! 
![it-worked](https://user-images.githubusercontent.com/4502942/59241085-a93e2900-8bdc-11e9-8d11-853a5caedf32.png)
