### ISSUE TITLE
Callbacks not working

### ISSUE THREAD

**Issue by FlavioFS** [FrogSquare/GodotGoogleService#22]
For some reason callbacks are not working. Any of them. Not even that ```Debug.log``` in line 13.  

Am I doing something wrong or is it still to be fixed? :thinking: 

![image](https://user-images.githubusercontent.com/4502942/59545800-87a1b200-8efa-11e9-80e1-29e028dfdd5f.png)
![image](https://user-images.githubusercontent.com/4502942/59545807-a43dea00-8efa-11e9-89a8-9a36e9c25004.png)

**Comment by RameshRavone** [comment]
Use this callback function

```
func _receive_message(tag, from, key, data):
    if tag == "FrogSquare":
        print("From: ", from, " Key: ", key, " Data: ", data)
```

**Comment by FlavioFS** [comment]
Good idea, but sadly it didn't work. The login window appears, the connection is supposed to fail and a "false" callback should appear.

![image](https://user-images.githubusercontent.com/4502942/59546069-94c0a000-8efe-11e9-9f41-30bbe3dd87e5.png)

**Comment by RameshRavone** [comment]
There is no callback for login failure..!

**Comment by FlavioFS** [comment]
# Sorry :sweat_smile: 

Oh, my bad! The false is at ```disconnect```, I misread it.

I guess there is no other way to test callbacks aside uploading a new version to Play Store and waiting another day for Google's approval. :sob:

Guess Imma code my own "connection_fail" callback (if possible)

**Comment by RameshRavone** [comment]
Actually you can create PR for connection fail callback under
`handleSignInResult` function..

**Comment by FlavioFS** [comment]
Ty, that's exactly what I was going for. :+1:

**Comment by FlavioFS** [comment]
Yeeey, it worked. Thanks. :grin: 
Now I can start coding for real.

![image](https://user-images.githubusercontent.com/4502942/59546422-8c1e9880-8f03-11e9-972c-5f9c53542e13.png)

Oh, one more thing. Your example seems to use an outdated tag:
![image](https://user-images.githubusercontent.com/4502942/59546439-def85000-8f03-11e9-92c1-6177a1f9513d.png)
