### ISSUE TITLE
Having trouble signing in. (SignInActivity: Sign in failed during 7)

### ISSUE THREAD

**Issue by Alpzy** [FrogSquare/GodotGoogleService#24]
Having a very similar issue to #6 submitted by @henriquelalves. I am using Godot 3.1, my log is as below:

`08-04 16:20:56.762 29260 29260 D FrogSquare: Play Service Available.`
`08-04 16:20:56.817 29260 29260 D FrogSquare: Google::Initialized`
`08-04 16:20:56.827 29260 29260 D FrogSquare: Google not connected`
`08-04 16:21:04.549 28371 28371 W SignInActivity: onSignInFailed()...`
`08-04 16:21:04.549 28371 28371 W SignInActivity: Sign in failed during 7`
`08-04 16:21:04.549 28371 28371 W SignInActivity: ==> Returning non-OK result: 10002`
`08-04 16:21:04.694 29260 29260 D FrogSquare: onActivityResult: reqCode=9001, resCode=0`
`08-04 16:21:04.695 29260 29260 W FrogSquare: SignInResult::Failed code=4, Message: null`

I am sure that I am using the correct keystore, and app id is set in `config.py` correctly.

The difference from @henriquelalves 's problem is that their log is as "SignInActivity: Sign in failed during 6" and mine is as "SignInActivity: Sign in failed during 7". Not sure what it means and if that would help.

**Comment by Alpzy** [comment]
**SOLVED**

As @vini-guerrero mentioned in issue #19 , I have modified `res/values/ids.xml` file with my app's ID and recompiled.

I strongly encourage you to update the README so people wouldn't struggle for days trying to figure out what might be causing the issue.

**Comment by kings2000** [comment]
> 
> 
> **SOLVED**
> 
> As @vini-guerrero mentioned in issue #19 , I have modified `res/values/ids.xml` file with my app's ID and recompiled.
> 
> I strongly encourage you to update the README so people wouldn't struggle for days trying to figure out what might be causing the issue.

please where can i get the app id

**Comment by Alpzy** [comment]
> > **SOLVED**
> > As @vini-guerrero mentioned in issue #19 , I have modified `res/values/ids.xml` file with my app's ID and recompiled.
> > I strongly encourage you to update the README so people wouldn't struggle for days trying to figure out what might be causing the issue.
> 
> please where can i get the app id

@kings2000 
1. Go to google play console.
2. Go to "Game Services".
3. Choose the application that you want to get the ID of.

The ID you're looking for should be below the app title. It's a 12 digit value. (i.e. 123456789012)
