### ISSUE TITLE
Execution failed for task ':compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by kings2000** [FrogSquare/GodotGoogleService#25]
godot-3.1.1-stable\platform\android\java\src\com\google\android\vending\expansion\downloader\impl\DownloadNotification.java:51: error: package NotificationCompat does not exist
        private NotificationCompat.Builder mActiveDownloadBuilder;
                                  ^
godot-3.1.1-stable\platform\android\java\src\com\google\android\vending\expansion\downloader\impl\DownloadNotification.java:52: error: package NotificationCompat does not exist
        private NotificationCompat.Builder mBuilder;
                                  ^
godot-3.1.1-stable\platform\android\java\src\com\google\android\vending\expansion\downloader\impl\DownloadNotification.java:53: error: package NotificationCompat does not exist
        private NotificationCompat.Builder mCurrentBuilder;
                                  ^
godot-3.1.1-stable\platform\android\java\src\org\godotengine\godot\Godot.java:62: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^
godot-3.1.1-stable\modules\FireBase\android\auth\AnonymousAuth.java:24: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
godot-3.1.1-stable\modules\FireBase\android\auth\Auth.java:22: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
godot-3.1.1-stable\modules\FireBase\android\auth\Auth.java:23: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
godot-3.1.1-stable\modules\FireBase\android\auth\EmailAndPassword.java:21: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
godot-3.1.1-stable\modules\FireBase\android\auth\GoogleSignIn.java:23: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
godot-3.1.1-stable\modules\FireBase\android\Firestore.java:26: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
godot-3.1.1-stable\modules\FireBase\android\MessagingService.java:28: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
godot-3.1.1-stable\modules\FireBase\android\Notification.java:27: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
godot-3.1.1-stable\modules\FireBase\android\NotifyInTime.java:24: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;;
                                 ^
godot-3.1.1-stable\modules\FireBase\android\auth\Auth.java:149: error: cannot find symbol
        @Nullable
         ^
  symbol:   class Nullable
  location: class Auth
godot-3.1.1-stable\modules\FireBase\android\auth\GoogleSignIn.java:242: error: cannot find symbol
        public void onConnectionFailed(@NonNull ConnectionResult m_result) {
                                        ^
  symbol:   class NonNull
  location: class GoogleSignIn
godot-3.1.1-stable\platform\android\java\src\com\google\android\vending\expansion\downloader\impl\DownloadNotification.java:207: error: package NotificationCompat does not exist
                mActiveDownloadBuilder = new NotificationCompat.Builder(ctx);
                                                               ^
godot-3.1.1-stable\platform\android\java\src\com\google\android\vending\expansion\downloader\impl\DownloadNotification.java:208: error: package NotificationCompat does not exist
                mBuilder = new NotificationCompat.Builder(ctx);
                                                 ^
godot-3.1.1-stable\platform\android\java\src\com\google\android\vending\expansion\downloader\impl\DownloadNotification.java:212: error: cannot find symbol
                mActiveDownloadBuilder.setPriority(NotificationCompat.PRIORITY_LOW);
                                                   ^
  symbol:   variable NotificationCompat
  location: class DownloadNotification
godot-3.1.1-stable\platform\android\java\src\com\google\android\vending\expansion\downloader\impl\DownloadNotification.java:213: error: cannot find symbol
                mActiveDownloadBuilder.setCategory(NotificationCompat.CATEGORY_PROGRESS);
                                                   ^
  symbol:   variable NotificationCompat
  location: class DownloadNotification
godot-3.1.1-stable\platform\android\java\src\com\google\android\vending\expansion\downloader\impl\DownloadNotification.java:215: error: cannot find symbol
                mBuilder.setPriority(NotificationCompat.PRIORITY_LOW);
                                     ^
  symbol:   variable NotificationCompat
  location: class DownloadNotification
godot-3.1.1-stable\platform\android\java\src\com\google\android\vending\expansion\downloader\impl\DownloadNotification.java:216: error: cannot find symbol
                mBuilder.setCategory(NotificationCompat.CATEGORY_PROGRESS);
                                     ^
  symbol:   variable NotificationCompat
  location: class DownloadNotification
godot-3.1.1-stable\platform\android\java\src\org\godotengine\godot\Godot.java:955: error: cannot find symbol
                        if (ContextCompat.checkSelfPermission(this, Manifest.permission.RECORD_AUDIO) != PackageManager.PERMISSION_GRANTED) {
                            ^
  symbol:   variable ContextCompat
  location: class Godot
godot-3.1.1-stable\platform\android\java\src\org\godotengine\godot\Godot.java:962: error: cannot find symbol
                        if (ContextCompat.checkSelfPermission(this, Manifest.permission.CAMERA) != PackageManager.PERMISSION_GRANTED) {
                            ^
  symbol:   variable ContextCompat
  location: class Godot
godot-3.1.1-stable\modules\FireBase\android\auth\AnonymousAuth.java:67: error: cannot find symbol
                        public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
                                                        ^
  symbol: class NonNull
godot-3.1.1-stable\modules\FireBase\android\auth\AnonymousAuth.java:93: error: cannot find symbol
                        public void onComplete(@NonNull Task<AuthResult> task) {
                                                ^
  symbol: class NonNull
godot-3.1.1-stable\modules\FireBase\android\auth\Auth.java:181: error: cannot find symbol
                        public void onComplete(@NonNull Task<GetTokenResult> task) {
                                                ^
  symbol: class NonNull
godot-3.1.1-stable\modules\FireBase\android\auth\EmailAndPassword.java:61: error: cannot find symbol
                        public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
                                                        ^
  symbol: class NonNull
godot-3.1.1-stable\modules\FireBase\android\auth\EmailAndPassword.java:83: error: cannot find symbol
                        public void onComplete(@NonNull Task<AuthResult> task) {
                                                ^
  symbol: class NonNull
godot-3.1.1-stable\modules\FireBase\android\auth\GoogleSignIn.java:95: error: cannot find symbol
                        public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
                                                        ^
  symbol: class NonNull
godot-3.1.1-stable\modules\FireBase\android\auth\GoogleSignIn.java:143: error: cannot find symbol
                                public void onResult(@NonNull Status status) {
                                                      ^
  symbol: class NonNull
godot-3.1.1-stable\modules\FireBase\android\auth\GoogleSignIn.java:158: error: cannot find symbol
                        public void onResult(@NonNull Status status) {
                                              ^
  symbol: class NonNull
godot-3.1.1-stable\modules\FireBase\android\auth\GoogleSignIn.java:211: error: cannot find symbol
                        public void onComplete(@NonNull Task<AuthResult> task) {
                                                ^
  symbol: class NonNull
godot-3.1.1-stable\modules\FireBase\android\Firestore.java:76: error: cannot find symbol
                        public void onComplete(@NonNull Task<QuerySnapshot> task) {
                                                ^
  symbol: class NonNull
godot-3.1.1-stable\modules\FireBase\android\Firestore.java:124: error: cannot find symbol
                        public void onFailure(@NonNull Exception e) {
                                               ^
  symbol: class NonNull
godot-3.1.1-stable\modules\FireBase\android\Firestore.java:142: error: cannot find symbol
                        public void onFailure(@NonNull Exception e) {
                                               ^
  symbol: class NonNull
godot-3.1.1-stable\modules\FireBase\android\MessagingService.java:109: error: package NotificationCompat does not exist
                NotificationCompat.Builder nBuilder = new NotificationCompat.Builder(context)
                                  ^
godot-3.1.1-stable\modules\FireBase\android\MessagingService.java:113: error: package NotificationCompat does not exist
                .setStyle(new NotificationCompat.BigPictureStyle()
                                                ^
godot-3.1.1-stable\modules\FireBase\android\MessagingService.java:109: error: package NotificationCompat does not exist
                NotificationCompat.Builder nBuilder = new NotificationCompat.Builder(context)
                                                                            ^
godot-3.1.1-stable\modules\FireBase\android\MessagingService.java:135: error: package NotificationCompat does not exist
                NotificationCompat.Builder nBuilder = new NotificationCompat.Builder(context)
                                  ^
godot-3.1.1-stable\modules\FireBase\android\MessagingService.java:135: error: package NotificationCompat does not exist
                NotificationCompat.Builder nBuilder = new NotificationCompat.Builder(context)
                                                                            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
41 errors

These keep coming up when i try to build please any idea what might be the cause
Here is my build.gradle config

buildscript {
	repositories {
		google()
		jcenter()
			maven {
	url 'https://maven.fabric.io/public'
	}
	maven {
	url 'https://maven.google.com'
	}
	maven {
	url 'https://oss.sonatype.org/content/repositories/snapshots'
	}

	}
	dependencies {
		classpath 'com.android.tools.build:gradle:3.2.1'
				classpath "com.google.gms:google-services:4.1.0"

	}
}

apply plugin: 'com.android.application'

allprojects {
    repositories {
	mavenCentral()
	google()
	jcenter()
		maven {
	url 'https://maven.fabric.io/public'
	}
	maven {
	url 'https://maven.google.com'
	}
	maven {
	url 'https://oss.sonatype.org/content/repositories/snapshots'
	}

    }
}
//
dependencies {
	implementation "com.android.support:support-core-utils:28.0.0"
	implementation('com.google.firebase:firebase-core:16.0.7'){exclude group: 'com.android.support' exclude module: 'support-v4'}
	implementation('com.google.firebase:firebase-auth:16.2.1'){exclude group: 'com.android.support' exclude module: 'support-v4'}
	implementation('com.google.android.gms:play-services-auth:16.0.1'){exclude group: 'com.android.support' exclude module: 'support-v4'}
	implementation('com.google.android.gms:play-services-games:16.0.0'){exclude group: 'com.android.support' exclude module: 'support-v4'}
	//implementation('com.google.android.gms:play-services-auth:+')
	implementation('com.google.firebase:firebase-ads:17.2.0'){exclude group: 'com.android.support' exclude module: 'support-v4'}
	implementation('com.google.firebase:firebase-messaging:17.6.0'){exclude group: 'com.android.support' exclude module: 'support-v4'}
	implementation('com.firebase:firebase-jobdispatcher:0.8.5'){exclude group: 'com.android.support' exclude module: 'support-v4'}
	implementation('com.google.firebase:firebase-firestore:18.2.0'){exclude group: 'com.android.support' exclude module: 'support-v4'}
	implementation('com.google.firebase:firebase-invites:16.1.0'){exclude group: 'com.android.support' exclude module: 'support-v4'}
	implementation ('com.google.android.gms:play-services-ads:16.0.0') { exclude group: 'com.android.support' }
	implementation 'commons-codec:commons-codec:1.12'
	implementation 'com.android.support:multidex:1.0.0'
}

android {

	lintOptions {
		abortOnError false
		disable 'MissingTranslation','UnusedResources'
	}

	compileSdkVersion 28
	buildToolsVersion "28.0.3"
	useLibrary 'org.apache.http.legacy'

	packagingOptions {
		exclude 'META-INF/LICENSE'
		exclude 'META-INF/NOTICE'
	}
	defaultConfig {
		minSdkVersion 18
		applicationId 'com.Kigos.HungryJax'
		targetSdkVersion 28
		multiDexEnabled true
	}
	// Both signing and zip-aligning will be done at export time
	buildTypes.all { buildType ->
		buildType.zipAlignEnabled false
		buildType.signingConfig null
	}
	sourceSets {
		main {
			manifest.srcFile 'AndroidManifest.xml'
			java.srcDirs = ['src'
				,'D:/apps/vv/module/godot-3.1.1/godot-3.1.1-stable/modules/FireBase/android','D:/apps/vv/module/godot-3.1.1/godot-3.1.1-stable/modules/FireBase/frogutils','D:/apps/vv/module/godot-3.1.1/godot-3.1.1-stable/modules/SQLBridge/android'
			]
			res.srcDirs = [
				'res'
				,'D:/apps/vv/module/godot-3.1.1/godot-3.1.1-stable/modules/FireBase/res'
			]
			aidl.srcDirs = [
				'aidl'
				
			]
			assets.srcDirs = [
				'assets'
				
			]
		}
		debug.jniLibs.srcDirs = [
			'libs/debug'
			
		]
		release.jniLibs.srcDirs = [
			'libs/release'
			
		]
	}

	applicationVariants.all { variant ->
		variant.outputs.all { output ->
			output.outputFileName = "../../../../../../../bin/android_${variant.name}.apk"
		}
	}
}

apply plugin: "com.google.gms.google-services"

**Comment by osimuka** [comment]
Looks like thesame issue I'm having, are you sing Godot 3.1.1 ?

**Comment by kings2000** [comment]
i tried 3.1.1 and 3.1.2 same issue

**Comment by kings2000** [comment]
now working.
i just upgraded google gradle plugin build to 3.3.0 and it works fine.

**Comment by osimuka** [comment]
> now working.
> i just upgraded google gradle plugin build to 3.3.0 and it works fine.

how do you do that?

**Comment by osimuka** [comment]
```
 dependencies {
                classpath 'com.android.tools.build:gradle:3.3.0'
                                classpath "com.google.gms:google-services:4.1.0"

        }
```
is this what you mean?
I did that and still got themsame error
What version is your gradle on ... Im using the 5.1.1

**Comment by kings2000** [comment]
> 
> 
> ```
>  dependencies {
>                 classpath 'com.android.tools.build:gradle:3.3.0'
>                                 classpath "com.google.gms:google-services:4.1.0"
> 
>         }
> ```
> 
> is this what you mean?
> I did that and still got themsame error
> What version is your gradle on ... Im using the 5.1.1

yes.
we could continue on your own tread #23

**Comment by osimuka** [comment]
> > ```
> >  dependencies {
> >                 classpath 'com.android.tools.build:gradle:3.3.0'
> >                                 classpath "com.google.gms:google-services:4.1.0"
> > 
> >         }
> > ```
> > 
> > 
> > is this what you mean?
> > I did that and still got themsame error
> > What version is your gradle on ... Im using the 5.1.1
> 
> yes.
> we could continue on your own tread #23

Thanks for the help, finally got it to work. 
- I removed my godot 3.1.1 install
- Added the module GodotSql
- Upgraded my Gradle to 4.10.1
- Also what you did upgraded my android gradle build to ```com.android.tools.build:gradle:3.3.0```
- It worked like charm 👍 💯
