### ISSUE TITLE
Sign in failed during 6

### ISSUE THREAD

**Issue by ghost** [FrogSquare/GodotGoogleService#31]
I'm trying to get google services to work in godot 1.3.1 and I have compiled the template but when running the apk, it doesn't sign in. I have checked the credentials again and again and still no luck. I have even tried to use other modules but no luck there either hopefully someone can spot something I have done wrong. Thank you

here is the developer console and adb logcat
![image](https://user-images.githubusercontent.com/22170909/69264813-fa0c7180-0bbf-11ea-9ca4-a5e030919db6.png)
![image](https://user-images.githubusercontent.com/22170909/69264854-0c86ab00-0bc0-11ea-8eed-cd23dc211f1e.png)

**Comment by RameshRavone** [comment]
Try this https://github.com/playgameservices/play-games-plugin-for-unity/issues/2045#issuecomment-350335234

**Comment by ghost** [comment]
> Try this [playgameservices/play-games-plugin-for-unity#2045 (comment)](https://github.com/playgameservices/play-games-plugin-for-unity/issues/2045#issuecomment-350335234)

Thank you for the quick response. Unfortunately, after creating the oAuth key in https://console.developers.google.com/apis and in https://play.google.com. The client ids did not end up being the same. Do you know why this is?

**Comment by ghost** [comment]
> Try this [playgameservices/play-games-plugin-for-unity#2045 (comment)](https://github.com/playgameservices/play-games-plugin-for-unity/issues/2045#issuecomment-350335234)

I don't know who you are. But I MUST thank you so much. I finally got it working after trying it again. Once again. Thank you!
