### ISSUE TITLE
Error Compiling for Android on MAC

### ISSUE THREAD

**Issue by felipemattar** [FrogSquare/GodotGoogleService#5]
I have this error after use the ./gradlew build:

Download https ://jcenter.bintray.com/com/android/support/support-v4/maven-metadata.xml
Download https ://dl.google.com/dl/android/maven2/com/android/support/support-v4/maven-metadata.xml
Download https ://maven.google.com/com/android/support/support-v4/maven-metadata.xml

> Configure project :
The setTestClassesDir(File) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the setTestClassesDirs(FileCollection) method instead.
The getTestClassesDir() method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the getTestClassesDirs() method instead.
The ConfigurableReport.setDestination(Object) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the method ConfigurableReport.setDestination(File) instead.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /.../godot-2.1/platform/android/java/src/debug/google-services.json
  /...godot-2.1/platform/android/java/google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
46 actionable tasks: 46 executed

**Comment by RameshRavone** [comment]
Follow [link](https://support.google.com/firebase/answer/7015592?hl=en) to download `google-services.json`

And place it under `platform/java/`

**Comment by felipemattar** [comment]
Tanks I get it, but now I get a new error:

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> No matching client found for package name 'XXXXXXX' 

The XXXXXXX is my app id (the number from google play console) witch I put on config.py file on module folder.

**Comment by RameshRavone** [comment]
Inspect the `google-services.json` files to confirm they have contain the correct package names,

**Comment by felipemattar** [comment]
it works now! tanks, I was using the app id number, but it was the com.xxxx.xxx name instead.

**Comment by felipemattar** [comment]
So I did, when the app open shows up the google play games screen connecting, it looks ok, but doesn't work at all. When I click to show achievements or leaderboards, the popup screen open but before it loads the content the popup closes and back to game. Im about to create a new app, project and game services on google console to try again. I was using kloder-games/godot-gpgs module, it was working fine, but it begins to became unstable, crashing the Google Play Services app. Any ideas?

**Comment by felipemattar** [comment]
Im using now one of my backups and its working fine, I must did something to mess-up so I will use that version for now. Tanks for the help.
