### ISSUE TITLE
Login auth failed: error 10002

### ISSUE THREAD

**Issue by henriquelalves** [FrogSquare/GodotGoogleService#6]
I successfully built the module to use on my Godot 2.0.4 game; it is able to at least try to connect using "google.login()", but adb returns an error:

`06-24 22:47:18.544 16217 16217 W SignInActivity: onSignInFailed()...
06-24 22:47:18.545 16217 16217 W SignInActivity: Sign in failed during 6
06-24 22:47:18.545 16217 16217 W SignInActivity: ==> Returning non-OK result: 10002
`

I believe the app is set up correctly on google play store, so I think this is a configuration error on my side. On `config.py`, is the app_id the same as the APK godot builds (as in `org.xxx.yyy`), or is related to the ID number Play Services gives me?

**Comment by RameshRavone** [comment]
`app_id = "com.example.game"` not the ID given by google play service

**Comment by henriquelalves** [comment]
Then I'm not sure what the error is about. I tried publishing the app (instead of just testing it), but it still gives the same error. I'm also using your firebase module, but it looks like it's working correctly unlike PlayServices.

**Comment by RameshRavone** [comment]
Can you provide the logcat, There might be some hint.

**Comment by henriquelalves** [comment]
Sure. The relevant part (Google Play Services log) is:

`06-24 23:26:37.337 20743 20743 D GoogleService: Play Service Available.
06-24 23:26:37.338 20743 20743 D GoogleService: Google::Initialized
06-24 23:26:37.355 20743 20743 D GoogleService: Google not connected
06-24 23:26:39.421 21081 21081 I SignInActivity: Transition from -1 to 0
06-24 23:26:43.208 21081 21081 I SignInActivity: Transition from 0 to 1
06-24 23:26:43.231 21081 21081 I SignInActivity: Transition from 1 to 3
06-24 23:26:43.326 21081 21081 I SignInActivity: Transition from 3 to 4
06-24 23:26:43.844 21081 21081 I SignInActivity: Transition from 4 to 5
06-24 23:26:43.866 21081 21081 I SignInActivity: Transition from 5 to 6
06-24 23:26:44.175 21081 21081 I SignInActivity: Transition from 6 to 11
06-24 23:26:44.175 21081 21081 W SignInActivity: onSignInFailed()...
06-24 23:26:44.175 21081 21081 W SignInActivity: Sign in failed during 6
06-24 23:26:44.175 21081 21081 W SignInActivity: ==> Returning non-OK result: 10002
06-24 23:26:44.723 20743 20743 D godot   : onActivityResult: reqCode=9001, resCode=0
06-24 23:26:44.723 20743 20743 W GoogleService: SignInResult::Failed code=12502, Message: null
06-24 23:26:44.724 20743 20743 D godot   : onActivityResult: reqCode=9001, resCode=0
06-24 23:26:44.724 20743 20743 W GoogleService: SignInResult::Failed code=4, Message: null
06-24 23:26:44.731 20743 20775 I godot   : From: Auth Key: GoogleLogin Data: false
`

EDIT: text formatting sucked, so I created a gist: https://gist.github.com/henriquelalves/6082dbee5fc481b02067453913df6a17

**Comment by henriquelalves** [comment]
I just found the problem!

I was using the debug keystore instead of the one my app uses on the .apk. I changed to the real keystore, and now it connects to the play services!

Closing the issue as the solution was found.
