### ISSUE TITLE
Update version to 11.8.0

### ISSUE THREAD

**Issue by ClaudioEden** [FrogSquare/GodotGoogleService#7]
When execute ./gradlew build to compile, a ERROR recommended to update version of 11.6.0 to 11.8.0 for this dependencies:

        env.android_add_dependency("compile 'com.google.android.gms:play-services-auth:11.6.0'")
        env.android_add_dependency("compile 'com.google.android.gms:play-services-games:11.6.0'")

	env.android_add_dependency("compile 'com.google.firebase:firebase-invites:11.6.0'")

**Comment by homarox** [comment]
I have this problem too, please fix it

**Comment by RameshRavone** [comment]
We are already using version `15.0.1`
