### ISSUE TITLE
Dependencies out of date

### ISSUE THREAD

**Issue by HummusSamurai** [FrogSquare/GodotGoogleService#8]
I get the same error I got in https://github.com/FrogSquare/GodotFireBase/issues/34#issue-359105746 that was partially solved by https://github.com/FrogSquare/GodotFireBase/commit/f454523066c571333ecbec65b617558ba0f03ea3

```
./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'java'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.google.firebase:firebase-core:15.0.1.
     Required by:
         project :
   > Could not find com.google.firebase:firebase-core:15.0.1.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
```

**Comment by RameshRavone** [comment]
This happens because there is no release for `firebase-core:15.0.1` and we don't use that in `GodotFireBase` or `GodotGoogleService` we are using `16.+`, So, the problem must be related to some other modules.
